import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#f7f9fc',
        'surface': '#f7f9fc',
        'surface-bright': '#f7f9fc',
        'surface-dim': '#d8dadd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'surface-container-high': '#e6e8eb',
        'surface-container-highest': '#e0e3e6',
        'surface-variant': '#e0e3e6',
        'surface-tint': '#0e5bbb',
        'on-surface': '#191c1e',
        'on-surface-variant': '#424752',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f4',
        'primary': '#004594',
        'primary-container': '#105cbc',
        'primary-fixed': '#d7e2ff',
        'primary-fixed-dim': '#acc7ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#cadaff',
        'on-primary-fixed': '#001a40',
        'on-primary-fixed-variant': '#004492',
        'inverse-primary': '#acc7ff',
        'secondary': '#4a6178',
        'secondary-container': '#cae2fe',
        'secondary-fixed': '#cee5ff',
        'secondary-fixed-dim': '#b1c9e4',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4e657c',
        'on-secondary-fixed': '#021d31',
        'on-secondary-fixed-variant': '#32495f',
        'tertiary': '#940010',
        'tertiary-container': '#bb1b21',
        'tertiary-fixed': '#ffdad6',
        'tertiary-fixed-dim': '#ffb3ac',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffceca',
        'on-tertiary-fixed': '#410003',
        'on-tertiary-fixed-variant': '#930010',
        'outline': '#727783',
        'outline-variant': '#c2c6d4',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Public Sans', 'system-ui', 'sans-serif'],
        headline: ['Public Sans', 'sans-serif'],
        body: ['Public Sans', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
    },
  },
  plugins: [],
};

export default config;
